import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>TheFlowX</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div style={{display:'flex', alignItems:'center'}}>
          <span style={{fontSize: 120, fontWeight:'bold'}} className={'gradientText'}>TheFlow</span>
          <span style={{fontSize: 180, color:'white', fontFamily:'monospace', fontWeight:'bolder'}} className={'spinnerX'}>X</span>
        </div>
        <span  style={{fontSize: 40, color:'white'}}>
          An Actions on blockchain Events using No-Code.
        </span>
        <button style={{cursor:'pointer', marginTop:25, fontSize: 25, padding:5, paddingLeft:25, paddingRight:25, borderRadius:30, fontWeight:'bold'}} onClick={()=>{
          location.replace("/editor/index.html")
        }}>Let's Go</button>
      </main>


    </div>
  )
}
